function find_value(matrix, value) {
    matrixLength = matrix.length;
    console.log(`Procurando por ${value} em ${matrixLength} registros!`);
    for (i = 0; i < matrixLength; i++) {
        if (matrix[i] == value) return true;
    }
    return false;
}

const users = [
    "Alice",
    "Sophia",
    "Arthur",
    "Helena",
    "Bernardo",
    "Valentina",
    "Heitor",
    "Laura",
    "Davi",
    "Isabella",
    "Lorenzo",
    "Manuela",
    "Théo",
    "Júlia",
    "Pedro",
    "Heloísa",
    "Gabriel",
    "Luiza",
    "Benjamin",
    "Maria",
    "Lucas",
    "Lívia",
    "Matheus",
    "Antônia",
    "Gustavo",
    "Eduarda",
    "João",
    "Clara",
    "Enzo",
    "Cecília",
    "Samuel",
    "Larissa",
    "Nicolas",
    "Larissa",
    "Rafael",
    "Sophie",
    "Guilherme",
    "Valentina",
    "Murilo",
    "Isadora",
    "Vitor",
    "Eloá",
    "Leonardo",
    "Yasmin",
    "Pedro",
    "Luana",
    "Felipe",
    "Juliana",
    "João",
    "Lorena",
    "Carlos",
    "Giovanna",
    "Rafael",
    "Fernanda",
    "Bruno",
    "Camila",
    "Daniel",
    "Carolina",
    "Luiz",
    "Mariana",
    "Caio",
    "Gabriela",
    "Vitor",
    "Amanda",
    "Natália",
    "Antônio",
    "Beatriz",
    "Leticia",
    "José",
    "Catarina",
    "Paulo",
    "Vitória",
    "Mateus",
    "Rafaela",
    "Murilo",
    "Bianca",
    "Diego",
    "Manoela",
    "Anderson",
    "Jéssica",
    "Matheus",
    "Raquel",
    "Lucas",
    "Carla",
    "Renan",
    "Tatiana",
    "André",
    "Paula",
    "Ricardo",
    "Lara",
    "Thiago",
    "Fernanda",
    "Alex",
    "Vanessa",
    "Luan",
    "Patrícia",
    "Vinícius",
    "Roberta",
    "Marcos",
    "Aline",
    "Raphael",
    "Juliana",
    "Leonardo",
    "Priscila",
    "Fernando",
    "Andressa",
    "Joaquim",
    "Renata",
    "Hugo",
    "Bárbara",
    "Sérgio",
    "Laís",
    "Francisco",
    "Mara",
    "Alan",
    "Marina",
    "Pedro",
    "Rebeca",
    "Vinícius",
    "Ana",
    "Emanuel",
    "Julia",
    "Raul",
    "Daniela",
    "Thiago",
    "Elisa",
    "Adriano",
    "Lívia",
    "Juliano",
    "Thaís",
    "Fábio",
    "Isis",
    "Rafael",
    "Alice",
    "Bruno",
    "Lívia",
    "Wagner",
    "Carolina",
    "Igor",
    "Kátia",
    "Afonso",
    "Ivete",
    "Marta",
    "Domingos",
    "Cláudia",
    "Artur",
    "Renata",
    "Márcio",
    "Tânia",
    "Hélio",
    "Sandra",
    "Israel",
    "Luíza",
    "Fernando",
    "Raquel",
    "Diogo",
    "Carla",
    "Julius",
    "Solange",
    "Rodrigo",
    "Soraya",
    "Mário",
    "Tatiana",
    "Marcelo",
    "Rita",
    "Roberto",
    "Leila",
    "José",
    "Fabiana",
    "Adriano",
    "Angélica",
    "Caio",
    "Lorena",
    "Felipe",
    "Karine",
    "Edson",
    "Elena",
    "Raul",
    "Renata",
    "Alexandre",
    "Silvia",
    "Sérgio",
    "Mirella",
    "Renato",
    "Lurdes",
    "Tiago",
    "Eliane",
    "José",
    "Mirela",
    "Gabriel",
    "Janaína",
    "Ricardo",
    "Vivian",
    "Guilherme",
    "Rafaela",
    "Samuel",
    "Elaine",
    "Felipe",
    "Aline",
    "Renan",
    "Fabíola",
    "Otávio",
    "Beatriz",
    "Marcelo",
    "Giovanna",
    "Adriana",
    "Diego",
    "Larissa",
    "Luiz",
    "Catarina",
    "Luan",
    "Helena",
    "Rodrigo",
    "Graziela",
    "Anderson",
    "Patrícia",
    "Rafael",
    "Daniela",
    "Caio",
    "Jéssica",
    "Daniel",
    "Carla",
    "Lucas",
    "Juliana",
    "Thiago",
    "Mariana",
    "Alex",
    "Leticia",
    "Renan",
    "Rafaela",
    "Amanda",
    "Carlos",
    "Bianca",
    "João",
    "Mariana",
    "José",
    "Camila",
    "Paulo",
    "Maria",
    "Matheus",
    "Carolina",
    "Antônio",
    "Larissa",
    "Rafael",
    "Beatriz",
    "Murilo",
    "Manoela",
    "Vitor",
    "Bianca",
    "Isaac",
    "Yasmin",
    "Bruno",
    "Juliana",
    "Vitor",
    "Fernanda",
    "Paulo",
    "Camila",
    "Mateus",
    "Mariana",
    "Felipe",
    "Maria",
    "João",
    "Carolina",
    "Larissa",
    "José",
    "Isadora",
    "Antônio",
    "Clara",
    "Gustavo",
    "Valentina",
    "Lucas",
    "Maria",
    "Rafael",
    "Ramon"
];

const username = "Ramon";
const start = performance.now();
if (find_value(users, username)) {
    console.log(`${username} está na lista!.`);
}

if (find_value(users, username)) {
    console.log(`${username} pode comer!.`);
}
const end = performance.now();
const executionTime = end - start;
console.log(`Tempo de execução ${executionTime}`);

/* Otimização: Já que o a mesma função é usada 2 vezes retornando o mesmo valor, podemos coloca-lá em uma variavel, sem precisar de refazer o teste */
const startOneIf = performance.now();
const authorized = find_value(users, username);

if (authorized) {
    console.log(`${username} está na lista!.`);
}

if (authorized) {
    console.log(`${username} pode comer!.`);
}
const endOneIf = performance.now();
const executionTimeOneIf = endOneIf - startOneIf;
console.log(`Tempo de execução ${executionTimeOneIf}`);
